<div class="header"><?php echo sprintf(_("Invoices of reseller: %s"), $reseller_data['name']) ?></div>
<table class="striped" style="width: 100%;">
<tr style="text-align: right;">
<th class="control"><?php echo _("Invoice") ?></th>
<th class="control"><?php echo _("Company") ?></th>
<th class="control"><?php echo _("Total bare") ?></th>
<th class="control"><?php echo _("Total tax") ?></th>
<th class="control"><?php echo _("Total") ?></th>
<th class="control"><?php echo _("Percentage") ?></th>
<th class="control"><?php echo _("Revenue") ?></th>
</tr>
